#!/bin/bash
# Tests the validation in apply-payload.sh. Runs as a normal user via --check,
# so nothing on the system is touched.
#
#   bash mac/test-apply-payload.sh

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT="$HERE/apply-payload.sh"
T=$(mktemp -d "${TMPDIR:-/tmp}/portcullis-test.XXXXXX")
trap 'rm -rf "$T"' EXIT

B="# >>> portcullis >>>"; E="# <<< portcullis <<<"
pass=0; fail=0

expect() {  # expect <accept|reject> <label> <file contents>
  printf '%s' "$3" > "$T/p"
  if bash "$SCRIPT" "$T/p" --check >/dev/null 2>&1; then got=accept; else got=reject; fi
  if [[ "$got" == "$1" ]]; then pass=$((pass+1)); echo "  ok   $2"
  else fail=$((fail+1)); echo "  FAIL $2 (expected $1, got $got)"; fi
}

expect accept "a normal block"                 "$B
# Generated by Portcullis
0.0.0.0 example.com
0.0.0.0 www.example.com
$E
"
expect accept "Windows line endings"           "$B"$'\r\n'"0.0.0.0 example.com"$'\r\n'"$E"$'\r\n'
expect reject "redirect a real site elsewhere" "$B
0.0.0.0 example.com
93.184.216.34 mybank.com
$E
"
expect reject "point a site at localhost"      "$B
127.0.0.1 mybank.com
$E
"
expect reject "a second name on one line"      "$B
0.0.0.0 example.com mybank.com
$E
"
expect reject "shell metacharacters"           "$B
0.0.0.0 example.com;rm
$E
"
expect reject "missing end marker"             "$B
0.0.0.0 example.com
"
expect reject "content outside the markers"    "127.0.0.1 evil
$B
0.0.0.0 example.com
$E
"
expect reject "duplicate begin marker"         "$B
$B
0.0.0.0 example.com
$E
"
expect reject "uppercase / invalid hostname"   "$B
0.0.0.0 EXAMPLE..com
$E
"
expect reject "a bare IP, no name"             "$B
0.0.0.0
$E
"
expect reject "empty file"                     ""

echo
echo "  $pass passed, $fail failed"
exit $(( fail > 0 ))
